version: '3.8'

services:
  # PHP / Laravel App
  app:
    build:
      context: ./ctij-api
      dockerfile: Dockerfile
    container_name: ctij-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./ctij-api:/var/www
    networks:
      - ctij-network
    depends_on:
      - db

  # Nginx Server
  nginx:
    image: nginx:alpine
    container_name: ctij-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./ctij-api:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - ctij-network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: ctij-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: cabinet_tij_db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ctij-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ctij-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "root"
    depends_on:
      - db
    networks:
      - ctij-network

  # Frontend App (React.js or similar)
  frontend:
    build:
      context: ./ctij-frontend
      dockerfile: Dockerfile
    container_name: ctij-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - ctij-network

  # SonarQube for code quality
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - ctij-network

# Named Volumes
volumes:
  dbdata:
    driver: local
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

# Docker Network
networks:
  ctij-network:
    driver: bridge
