services:
  frontend:
    build:
      context: ./ctij-frontend
    command: ["npm", "run", "build"]  # Build React app
    volumes:
      - ./ctij-frontend/build:/usr/share/nginx/html  # Mount the build output to Nginx
    networks:
      - ctij-staging

  backend:
    build:
      context: ./ctij-api
    env_file:
      - ./ctij-api/.env.staging
    depends_on:
      - mysql
    ports:
      - "8001:8000"
    networks:
      - ctij-staging

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ctij_staging
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_staging_data:/var/lib/mysql
    networks:
      - ctij-staging

  nginx:
    build:
      context: ./nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ctij-frontend/build:/usr/share/nginx/html  # Ensure that build folder is mounted
    depends_on:
      - frontend
      - backend
    networks:
      - ctij-staging

networks:
  ctij-staging:

volumes:
  mysql_staging_data:
