  frontend:
    build: ./ctij-frontend
    container_name: react_frontend
    restart: always
    networks:
      - app-network
    # REMOVE this line to let Docker use the built image:
    # volumes:
    #   - ./ctij-frontend/dist:/usr/share/nginx/html:ro

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: always
    depends_on:
      - laravel
      - frontend
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d
