version: '3.8'

services:
  backend:
    build:
      context: ./ctij-api
    container_name: laravel-api
    volumes:
      - ./ctij-api:/var/www
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: cabinet_tij_db
      DB_USERNAME: root
      DB_PASSWORD: 
    depends_on:
      - db
    networks:
      - appnet

  # frontend:
  #   build:
  #     context: ./ctij-frontend
  #   container_name: react-app
  #   volumes:
  #     - ./ctij-frontend:/app
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     - appnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ctij-api/public:/var/www/public
      - ./ctij-frontend/build:/usr/share/nginx/html
    depends_on:
      - backend   # Changed to 'backend' to match the service name
      # - frontend
    networks:
      - appnet

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cabinet_tij_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet

volumes:
  dbdata:

networks:
  appnet:
    driver: bridge
