# Use an official Node image
FROM node:16

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json before installing dependencies
COPY ctij-frontend/package.json ctij-frontend/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend files
COPY ctij-frontend/ ./

# Build the app
RUN npm run build

# Expose port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
