name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up SSH agent with your VPS private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      # Deploy to VPS via SSH
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_HOST }} << 'EOF'
            set -e

            echo ">>> Pulling latest code..."
            cd /var/www/cabinet-tij
            git pull origin main

            echo ">>> Building frontend..."
            cd ctij-frontend
            npm install
            npm run build
            cd ..

            echo ">>> Rebuilding Docker containers..."
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d --build

            echo ">>> Deployment complete!"
          EOF
